"""Initial migration

Revision ID: 563f417af01c
Revises: 
Create Date: 2024-10-03 14:24:19.382900

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '563f417af01c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
